

<!--<form action="--><?php //echo $this->getUrl('*/*/generateCategoryRelations') ?><!--" method="post">-->
<!--    <input name="form_key" type="hidden" value="--><?php //echo $this->getFormKey() ?><!--" />-->
<!--    <button class="scalable" type="submit"><span>Generate category relations</span></button>-->
<!--</form>-->
<?
phpinfo();
?>
<form action="<?php echo $this->getUrl('*/*/importCategories') ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
    <button class="scalable" type="submit"><span>Import categories</span></button>
</form>

<form action="<?php echo $this->getUrl('*/*/importAttributes') ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
    <button class="scalable" type="submit"><span>Import attributes</span></button>
</form>

<form action="<?php echo $this->getUrl('*/*/importProducts') ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
    <button class="scalable" type="submit"><span>Import products</span></button>
</form>

<form action="<?php echo $this->getUrl('*/*/importResources') ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
    <button class="scalable" type="submit"><span>Import resources</span></button>
</form>

<form action="<?php echo $this->getUrl('*/*/importPrices') ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
    <button class="scalable" type="submit"><span>Import prices</span></button>
</form>