<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */

/**
 * This page is does not exist in /base/default
 * Modified to place category title block above sidebar filter and product list
 *
 * derived functionality from: /template/catalog/category/view.phtml
 */
?>
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>

<h1>Fuck YOU!</h1>